import fs from "fs";
import path from "path";

const CSV_PATH = path.join(process.cwd(), "audit", "search-console-pages.csv");
const OUTPUT_PATH = path.join(process.cwd(), "lib", "guide-rankings.ts");

const csv = fs.readFileSync(CSV_PATH, "utf-8");
const lines = csv.trim().split("\n").slice(1); // skip header

// Redirect mappings: old WP slug → new Next.js slug
const REDIRECTS: Record<string, string> = {
  "how-to-build-retreat-itineraries": "retreat-itinerary-planning-for-group-trips",
  "how-to-be-a-great-tour-guide-tips-and-trade-secrets-for-beginners": "how-to-be-a-great-tour-guide",
  "diy-wellness-retreat": "diy-wellness-retreat-plan-your-own-at-home-self-care-escape",
  "the-best-places-for-a-retreat": "find-the-best-places-to-host-a-retreat",
  "how-to-market-your-wellness-retreat-and-sell-out-fast": "how-to-host-a-wellness-retreat-that-sells-out",
  "best-travel-agent-tools-for-trip-management": "travel-agent-tools",
  "best-travel-agent-software-for-group-trip-reservations": "travel-agent-software",
  "the-wellness-tourism-market": "wellness-tourism-market-guide-for-practitioners",
  "retreat-marketing-tips-for-hosts-who-want-real-results": "marketing-a-retreat-in-2025-tips-for-hosts-who-want-real-results",
  "best-tour-booking-sites-what-they-get-right-and-how-to-cop": "best-tour-booking-sites-what-they-get-right-and-how-to-copy-them",
};

const clickMap: Record<string, number> = {};

for (const line of lines) {
  const match = line.match(/^(https?:\/\/[^,]+),(\d+),/);
  if (!match) continue;

  const url = match[1];
  const clicks = parseInt(match[2], 10);

  // Skip non-main-domain and Spanish URLs
  if (url.includes("/es/")) continue;

  // Extract guide slug (strip hash fragments)
  const guideMatch = url.match(
    /^https:\/\/(?:www\.)?squadtrip\.com\/guides\/([^#?,/]+)/
  );
  if (!guideMatch) continue;

  let slug = guideMatch[1];

  // Map old redirected slugs to current Next.js slugs
  if (REDIRECTS[slug]) {
    slug = REDIRECTS[slug];
  }

  clickMap[slug] = (clickMap[slug] || 0) + clicks;
}

// Sort descending by clicks
const sorted = Object.entries(clickMap).sort((a, b) => b[1] - a[1]);

// Build output
const lines_out: string[] = [];
lines_out.push("/**");
lines_out.push(" * Guide click rankings from Google Search Console.");
lines_out.push(" * Data period: Last 16 months (as of March 2026).");
lines_out.push(" * Generated by: npm run build-guide-rankings");
lines_out.push(" */");
lines_out.push("export const GUIDE_CLICKS: Record<string, number> = {");
for (const [slug, clicks] of sorted) {
  if (clicks > 0) {
    lines_out.push(`  "${slug}": ${clicks},`);
  }
}
lines_out.push("};\n");

fs.writeFileSync(OUTPUT_PATH, lines_out.join("\n"), "utf-8");

console.log(`Wrote ${sorted.filter(([, c]) => c > 0).length} guide rankings to ${OUTPUT_PATH}`);
console.log("\nTop 10:");
for (const [slug, clicks] of sorted.slice(0, 10)) {
  console.log(`  ${clicks.toString().padStart(5)} - ${slug}`);
}
